# reduce delay of key stroke
set -sg escape-time 1

# begin index of window from 1
set -g base-index 1

# begin index of pane from 1
setw -g pane-base-index 1

# rireki
set-option -g history-limit 5000000

# reload tmux config file
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# set prefix key
set-option -g prefix C-k
# cancel the key bindings for C-b
unbind-key C-b
bind-key C-k send-prefix

# split the pane with a pipe in a vertical
bind v split-window -h

# split the pane with a pipe in a transverse
bind w split-window -v

#起動シェルを指定
set-option -g default-shell /bin/zsh

# move between the panes in the key bindings for vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

#256色端末を使用
#"screen-256color" にするとvimの<Home><End>が変わるのでxtermに変更
#set-option -g default-terminal "screen-256color"
set-option -g default-terminal "xterm"
set-option -g xterm-keys on

# set status bar
## set the left panel
set -g status-left-length 40
set -g status-left "#[fg=red]Session: #S #[fg=yellow]#I #[fg=cyan]#P"
## set the right panel
set -g status-right-length 100
set -g status-right '#[fg=cyan][%Y-%m-%d(%a) %H:%M]'
## set the refresh interval (default 15 seconds)
set -g status-interval 60
## center shifting the position of the window list
set -g status-justify centre
## enable the visual notification
setw -g monitor-activity on
set -g visual-activity on
## display the status bar at the top
set -g status-position top

# set the copy mode
## use the key bindings for vi
setw -g mode-keys vi
## enable clipboard sharing
#set-option -g default-command "reattach-to-user-namespace -l zsh"
## set the operation of the copy mode to vim-style
#bind-key -t copy-mode-vi v begin-selection
#bind-key -t copy-mode-vi y copy-pipe "reattach-to-user-namespace pbcopy"
#unbind -t copy-mode-vi Enter
#bind-key -t copy-mode-vi Enter copy-pipe "reattach-to-user-namespace pbcopy"

#Powerline
run-shell "powerline-daemon -q"
source "/usr/share/powerline/bindings/tmux/powerline.conf"

